Add storage opts
buildkite-plugins/docker-buildkite-plugin pull request #181
Opened 2021-01-22 15:08 UTC by bennetty

add storage opts flag

2022-03-03 00:32 UTC, nithyaasworld commented
Thanks @bennetty for the PR! Sorry that it took us a long time to get to this. We verified it and we would be merging this soon. 

Could you also please update the Readme file with an example for this? Thanks again!

2022-03-29 13:47 UTC, nithyaasworld commented
While the plugin works, the [storage-opts flag](https://docs.docker.com/engine/reference/commandline/run/#set-storage-driver-options-per-container) is added as an array though it supposed to have only one value. Closing this PR. @bennetty  If you would like, please feel free to re-open this PR with updated changes that would accept storage-opts flag as string rather than an array.

2022-04-07 20:44 UTC, pzeballos requested changes
Only a small change on the README, but the rest LGTM

2022-04-07 20:44 UTC, pzeballos commented on plugin.yml
> +      type: string
Makes sense! 👌
We probably should order attributes in alphabetical order ... but that's outside this PR

2022-04-07 20:44 UTC, pzeballos commented on README.md
> +This allows to set the container rootfs size at the creation time. This is only available for the devicemapper, btrfs, overlay2, windowsfilter and zfs graph drivers. See [docker documentation](https:
I would add a backtick on each driver name:

```suggestion
This allows setting the container rootfs size at the creation time. This is only available for the `devicemapper`, `btrfs`, `overlay2`, `windowsfilter` and `zfs` graph drivers. See [docker documentation](https://docs.docker.com/engine/reference/commandline/run/#set-storage-driver-options-per-container) for more details.
```

2022-04-08 19:31 UTC, pzeballos approved these changes

2022-04-08 23:18 UTC, pzeballos commented
Thanks @bennetty for your contributions and sorry for the delay!!

2022-04-08 23:19 UTC, merged