`env-propagation-list`: programmatically propagate envvars to the container
buildkite-plugins/docker-buildkite-plugin pull request #238
Opened 2023-02-26 19:33 UTC by edmund-huber

Hi! Like many others, https://github.com/buildkite-plugins/docker-buildkite-plugin/issues/184 , I tried setting env vars in a hook, then was surprised when `propagate-environment` didn't propagate them to the container.

Here is my proposal for how to fix this. Instead of changing the behavior of `propagate-environment`, add a new option `env-propagation-list`, which:
> If you set this to `VALUE`, and `VALUE` is an environment variable containing a space-separated list of environment variables such as `A B C D`, then A, B, C, and D will all be propagated to the container. This is helpful when you've set up an `environment` hook to export secrets as environment variables, and you'd also like to programmatically ensure that secrets get propagated to containers, instead of listing them all out.

Here's how to use it: in your `environment` hook, where you would normally be generating bash statements like:
```
export SECRET_1="one"
export SECRET_2="two"
```
You can instead do:
```
export SECRET_1="one"
export PROPAGATE_LIST="SECRET_1 ${PROPAGATE_LIST:-}"
export SECRET_2="two"
export PROPAGATE_LIST="SECRET_2 ${PROPAGATE_LIST:-}"
```
Then, when you invoke this plugin, give it `propagate-list: 'PROPAGATE_LIST'`, and those vars you set will end up in the container, too.

2023-02-26 19:38 UTC, edmund-huber commented
I forgot to mention: I'm opening this PR because listing envvars you want to propagate manually in every step that uses docker-plugin and needs envvars is pretty annoying and error-prone.

2023-02-27 05:06 UTC, toote requested changes
This is a very interesting feature!

The one thing I would change is to define, implement, document and test the behaviour of when the configured variable does not exist. Right now, the execution explodes with:

```
/plugin/hooks/command: line 316: !BUILDKITE_PLUGIN_DOCKER_ENV_PROPAGATION_LIST: unbound variable
```

That I think is less than ideal

2023-02-27 21:13 UTC, edmund-huber commented
How's this?

2023-02-27 22:14 UTC, toote approved these changes

2023-02-27 22:15 UTC, merged

2023-05-05 17:28 UTC, amartani commented
I opened https://github.com/buildkite-plugins/docker-compose-buildkite-plugin/pull/388 to implement this feature for the docker-compose plugin, as it would be useful there as well. Thanks!